@extends('layouts.app')
@section('title','Detail Pengaduan')
@section('page_title','Detail Pengaduan')
@section('content')
<div class="row g-4">
    <div class="col-lg-7"><div class="content-card p-4"><div class="d-flex justify-content-between gap-3"><div><h4 class="fw-bold">{{ $complaint->title }}</h4><p class="text-muted mb-2">{{ $complaint->category->category_name }} • Pelapor: {{ $complaint->user->name }}</p></div>@include('partials.status-badge',['status'=>$complaint->status])</div>@if($complaint->photo)<img src="{{ asset('storage/'.$complaint->photo) }}" class="img-fluid rounded-4 my-3" alt="Foto bukti">@endif<p>{{ $complaint->description }}</p><hr><h6>Lokasi</h6><p class="mb-1">{{ $complaint->address }}</p><p class="text-muted">{{ $complaint->village_name }}, {{ $complaint->district_name }}, {{ $complaint->regency_name }}, {{ $complaint->province_name }}</p><div id="map-picker" class="map-picker"></div><input type="hidden" id="latitude" value="{{ $complaint->latitude }}"><input type="hidden" id="longitude" value="{{ $complaint->longitude }}"></div></div>
    <div class="col-lg-5"><div class="content-card p-4 mb-4"><h5 class="fw-bold">Ubah Status & Tanggapan</h5><form method="POST" action="{{ route('admin.complaints.update',$complaint) }}">@csrf @method('PUT')<div class="mb-3"><label class="form-label">Status</label><select class="form-select" name="status">@foreach($statuses as $status)<option value="{{ $status }}" @selected($complaint->status===$status)>{{ $status }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Tanggapan</label><textarea class="form-control" name="response" rows="4" placeholder="Opsional, isi jika ingin memberi tanggapan"></textarea></div><button class="btn btn-coral">Simpan Status</button></form></div><div class="content-card p-4"><h5 class="fw-bold mb-3">Riwayat Tanggapan</h5>@forelse($complaint->responses as $response)<div class="border-start border-3 ps-3 mb-3" style="border-color: var(--coral)!important"><div class="fw-semibold">{{ $response->admin->name }}</div><small class="text-muted">{{ $response->response_date->format('d/m/Y') }}</small><p class="mt-2 mb-0">{{ $response->response }}</p></div>@empty<p class="text-muted">Belum ada tanggapan.</p>@endforelse</div></div>
</div>
@endsection
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>window.initLocationPicker({latitude:@json($complaint->latitude),longitude:@json($complaint->longitude)}));</script>@endpush
